Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/09/2022
Var
  VALOR,N,CT: INTEIRO

Inicio

escreval ("Tabuada")
n <- 1
escreval ("Digite um número: ")
leia (VALOR)
para CT <- 1 ate 10 faca
  escreval (N," x",VALOR*N)
  N <- N + 1
fimpara


Fimalgoritmo